### ISSUE TITLE
Please tag a new release

### ISSUE THREAD

**Issue by fd0** [elithrar/simple-scrypt#10]
Hi,

we've recently switched to using [`dep`](https://github.com/golang/dep) and I've discovered that the last released version ("v1.1") is really old already and does not include my fix for i386 (#6).

Can you please tag a new release? Would you mind switching to semantic versioning for that? I.e. tag the next release as 1.2.0?

Thanks!

**Comment by elithrar** [comment]
Done - https://github.com/elithrar/simple-scrypt/releases/tag/v1.2.0

**Comment by fd0** [comment]
Great, thanks!
