### ISSUE TITLE
Do not calibrate r

### ISSUE THREAD

**Issue by FiloSottile** [elithrar/simple-scrypt#12]
[_r_ is not a memory parameter](https://blog.filippo.io/the-scrypt-parameters/), it's a cache parameter. Scaling _r_ scales both memory **and CPU**, just like _N_.

So halving _r_ has the exact same effect as halving _N_, except it makes scrypt less cache efficient on general purpose processors, artificially increasing is CPU requirements. ASICs would probably not pay that tax, though.

I recommend just fixing _r_ to 8, as cache line size is the same now as it was when the scrypt paper came out. If you want to increase CPU time without increasing memory, use _p_, as the Go implementation acts sequentially.

**Comment by elithrar** [comment]
Thanks Filippo! I’ve got a busy couple of weeks ahead, so won’t have time
to address until after, but will look to fix.

(PRs accepted) 😉

**Comment by LouisChrist** [comment]
I am currently working on a solution. It's already working, but very slow. Optimizing it should be trivial. I'll send a PR after i fixed that.

**Comment by elithrar** [comment]
Thanks Louis! Once you have a PR, we can review, and I can tag a new minor
release so that Restic can vendor the updated version.

**Comment by elithrar** [comment]
Fixed in https://github.com/elithrar/simple-scrypt/pull/13
