### ISSUE TITLE
Tests and calibration fails on Linux/i386

### ISSUE THREAD

**Issue by fd0** [elithrar/simple-scrypt#6]
Hi,

First: thanks for writing `simple-scrypt`! I'm using it for [restic](https://github.com/restic/restic), a secure and fast backup program.

A few days ago a user reported (https://github.com/restic/restic/issues/676) that restic fails with a mysterious error message:
```
create key in backend at /tmp/foo failed: Calibrate: scrypt.Calibrate: scrypt: the parameters provided are invalid
```

Building a 32 bit binary for restic and running it indeed produces invalid parameters, e.g. on my machine (rather recent Intel i5 CPU on a Thinkpad t460) `Calibrate()` returns the following values:
```
{N:1073741824 R:8 P:1 SaltLen:16 DKLen:32}
```
These parameters are (obviously) considered invalid.

In addition I've discovered that the tests fail on 386:
``
$ GOARCH=386 go test -v                          
# github.com/elithrar/simple-scrypt
./scrypt_test.go:26: constant 2147483648 overflows int
./scrypt_test.go:30: constant 2147483648 overflows int
FAIL	github.com/elithrar/simple-scrypt [build failed]
```
Thanks!

**Comment by elithrar** [comment]
Let me take a look. It's not immediately obvious what the fix is for 32-bit
systems, especially in a way that doesn't change the types of the public
API to int64 explicitly.

**Comment by fd0** [comment]
Maybe it's an option to use an `int64` for the calculations only...

**Comment by elithrar** [comment]
It's not (because other APIs accept untyped ints, including scrypt.Key
itself). How critical is 32-bit support here?

**Comment by fd0** [comment]
I think it's very valuable to fix the calibration to also work on 32 bit. I haven't heart any reports from other users trying out restic on 32 bit, but that may just mean that these other users gave up and did not report anything.

I can have a look later today and try to find out why the calibration fails. I have a hunch that it should be easy to correct for 32 bit...

**Comment by fd0** [comment]
Huh, this issue gets even weirder: On my Raspberry Pi 3 (also 32 bit, but ARM) the calibration works.

**Comment by elithrar** [comment]
What parameters are you calibrating for?

**Comment by fd0** [comment]
I'm calling `Calibrate()` with a timeout of 500ms and a memory usage of 69 MiB.

**Comment by elithrar** [comment]
How is restic calling it? It's likely that - with high enough values - the
value of P becomes too high and exceeds the max int on 386.

**Comment by fd0** [comment]
I've found the cause, this comparison for the for loop fails on 32 bit: https://github.com/elithrar/simple-scrypt/blob/master/scrypt.go#L263

restic calls `Calibrate(500ms, 60MiB, DefaultParams{N: 16384, R: 8, P: 1}`. On my machine, the first [call to `scrypt.Key()`](https://github.com/elithrar/simple-scrypt/blob/master/scrypt.go#L247) takes ~160ms, so `p.N` is [set to `0x40000000`](https://github.com/elithrar/simple-scrypt/blob/master/scrypt.go#L252-L254).

The left side of the condition in the [`for` loop](https://github.com/elithrar/simple-scrypt/blob/master/scrypt.go#L263) then evaluates to zero on 32 bit systems: `p.N * 8 * 128 = 0x40000000 * 8 * 128 = 0x10000000000 = 0`, so the loop's body is not run and `p.N` stays at `0x40000000`, so `Check()` [rejects it](https://github.com/elithrar/simple-scrypt/blob/master/scrypt.go#L143) (the last condition is true: `p.N == 0x40000000 >  maxInt/128/p.R == 0x1fffff`)

I've opened #7 which computes the condition in the `for` loop for 64 bit integers.

On my Raspberry Pi, the first call to `scrypt.Key()` takes longer than 500ms, so `p.N` is never touched and stays at the default value of 16384. In this case, the calculation of the condition in the `for` loop does not overflow an `int32`.

**Comment by elithrar** [comment]
Thanks for the PR @fd0, and for working through this! (just got back home after a week working away)
