### ISSUE TITLE
TestCalibrate fails sometimes

### ISSUE THREAD

**Issue by legrostdg** [elithrar/simple-scrypt#8]
TestCalibrate seems to fail with "0. GenerateFromPassword was too fast" sometimes:

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=851723
https://people.debian.org/~sanvila/build-logs/golang-github-elithrar-simple-scrypt/

**Comment by legrostdg** [comment]
`simple-scrypt` build is not reproducible because of this error.
https://tests.reproducible-builds.org/debian/rb-pkg/unstable/amd64/golang-github-elithrar-simple-scrypt.html

**Comment by elithrar** [comment]
Thanks for the report. I haven't got time to look at this right now, but
open to PRs that may resolve it.

**Comment by legrostdg** [comment]
A simple fix would be to disable the test (what will probably happen on the debian package if it's not fixed)... I have not enough understanding to write a proper fix.

**Comment by elithrar** [comment]
I won't be able to disable the test.

What drives the motivation to package this as a Debian package and not use
the existing Go tool chain?

**Comment by legrostdg** [comment]
`simple-scrypt` is used by `restic`, so if we want to have a package for `restic` in Debian, we need to have a package for `simple-scrypt`.

**Comment by legrostdg** [comment]
Is there any news on this issue? No problem if there is none, it's just to know if I disable the test in the Debian package or if it's worth waiting for a fix.

**Comment by elithrar** [comment]
@legrostdg Apologies for the (very) long delay. The tests are now more flexible about run-time (given that CI environments can be heavily loaded) - see https://github.com/elithrar/simple-scrypt/pull/13
